version: '3'
services:
  mongodb:
    image: "mongo"
    container_name: mongo
    ports:
      - "27017:27017"
  web:
    build: .
    container_name: backend
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./server:/server
    depends_on:
      - mongodb
  db_admin:
    image: "mrvautin/adminmongo"
    container_name: db_admin
    ports:
      - "1234:1234"
    environment:
      HOST: 0.0.0.0
